### ISSUE TITLE
Project 2 Review

### ISSUE THREAD

**Issue by flamingveggies** [eeronomicon/hackoregon-js-week5#1]
Great stuff! You might find it easier to work with the prototype inside your module if instead of renaming all the instances to `exports.Vehicle` you leave it as `Vehicle` and then just remember to export your finished prototype at the end with `exports.Vehicle = Vehicle`.

**Comment by eeronomicon** [comment]
Thank you! I've updated the code with those changes. Makes total sense that it'd work like that!
